export const packages = [
  {
    id: "beach-escape-bali",
    title: "Beach Escape",
    place: "Bali, Indonesia",
    category: "Beach",
    packageType: "Group",
    flight: "With Flight",
    theme: "Beach",
    priceValue: 120,
    price: "$120 / person",
    oldPrice: "$180",
    amount: "$120",
    duration: "3N / 4D",
    subtitle: "3 Nights Bali",
    highlights: ["Beach stay", "Island tour", "4 Star Accommodation"],
    image: "https://images.pexels.com/photos/2474690/pexels-photo-2474690.jpeg"
  },
  {
    id: "goa-beach-holiday",
    title: "Goa Beach Holiday",
    place: "Goa, India",
    category: "Beach",
    packageType: "Family",
    flight: "With Flight",
    theme: "Beach",
    priceValue: 90,
    price: "$90 / person",
    oldPrice: "$150",
    amount: "$90",
    duration: "3N / 4D",
    subtitle: "3N Goa",
    highlights: ["Fort Aguada", "Calangute Annexe", "Water Sports"],
    image: "https://images.pexels.com/photos/1078983/pexels-photo-1078983.jpeg"
  },
  {
    id: "city-discovery-paris",
    title: "City Discovery",
    place: "Paris, France",
    category: "City",
    packageType: "Couple",
    flight: "Without Flight",
    theme: "Culture",
    priceValue: 200,
    price: "$200 / person",
    oldPrice: "$260",
    amount: "$200",
    duration: "4N / 5D",
    subtitle: "4N Paris",
    highlights: ["City walk", "Museum pass", "Central hotel"],
    image: "https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg"
  },
  {
    id: "island-retreat-maldives",
    title: "Island Retreat",
    place: "Maldives",
    category: "Island",
    packageType: "Honeymoon",
    flight: "With Flight",
    theme: "Luxury",
    priceValue: 250,
    price: "$250 / person",
    oldPrice: "$330",
    amount: "$250",
    duration: "4N / 5D",
    subtitle: "4 Nights Maldives",
    highlights: ["Water villa", "Speedboat transfer", "Breakfast"],
    image: "https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg"
  },
  {
    id: "desert-luxury-dubai",
    title: "Desert Luxury",
    place: "Dubai, UAE",
    category: "Luxury",
    packageType: "Luxury",
    flight: "With Flight",
    theme: "Luxury",
    priceValue: 300,
    price: "$300 / person",
    oldPrice: "$390",
    amount: "$300",
    duration: "4N / 5D",
    subtitle: "4N Dubai",
    highlights: ["Desert safari", "Marina cruise", "Luxury hotel"],
    image: "https://images.pexels.com/photos/3787839/pexels-photo-3787839.jpeg"
  },
  {
    id: "mountain-adventure-swiss-alps",
    title: "Mountain Adventure",
    place: "Swiss Alps, Switzerland",
    category: "Adventure",
    packageType: "Adventure",
    flight: "Without Flight",
    theme: "Adventure",
    priceValue: 280,
    price: "$280 / person",
    oldPrice: "$360",
    amount: "$280",
    duration: "5N / 6D",
    subtitle: "5N Switzerland",
    highlights: ["Mountain rail", "Lake tour", "Alpine stay"],
    image: "https://images.pexels.com/photos/355770/pexels-photo-355770.jpeg"
  },
  {
    id: "safari-journey-serengeti",
    title: "Safari Journey",
    place: "Serengeti, Tanzania",
    category: "Wildlife",
    packageType: "Group",
    flight: "With Flight",
    theme: "Wildlife",
    priceValue: 340,
    price: "$340 / person",
    oldPrice: "$430",
    amount: "$340",
    duration: "5N / 6D",
    subtitle: "5N Tanzania",
    highlights: ["Game drive", "Camp stay", "Guide included"],
    image: "https://images.pexels.com/photos/26743186/pexels-photo-26743186.jpeg"
  },
  {
    id: "northern-lights-iceland",
    title: "Northern Lights",
    place: "Reykjavik, Iceland",
    category: "Nature",
    packageType: "Couple",
    flight: "With Flight",
    theme: "Nature",
    priceValue: 260,
    price: "$260 / person",
    oldPrice: "$340",
    amount: "$260",
    duration: "4N / 5D",
    subtitle: "4N Iceland",
    highlights: ["Aurora hunt", "Lagoon visit", "Transfers"],
    image: "https://images.pexels.com/photos/1933239/pexels-photo-1933239.jpeg"
  },
  {
    id: "historic-escape-rome",
    title: "Historic Escape",
    place: "Rome, Italy",
    category: "Culture",
    packageType: "Family",
    flight: "Without Flight",
    theme: "Culture",
    priceValue: 190,
    price: "$190 / person",
    oldPrice: "$250",
    amount: "$190",
    duration: "3N / 4D",
    subtitle: "3N Rome",
    highlights: ["Colosseum tour", "Old city walk", "Breakfast"],
    image: "https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg"
  },
  {
    id: "harbor-break-sydney",
    title: "Harbor Break",
    place: "Sydney, Australia",
    category: "City",
    packageType: "Group",
    flight: "With Flight",
    theme: "City",
    priceValue: 220,
    price: "$220 / person",
    oldPrice: "$290",
    amount: "$220",
    duration: "4N / 5D",
    subtitle: "4N Sydney",
    highlights: ["Harbor cruise", "City tour", "Beach visit"],
    image: "https://images.pexels.com/photos/1878293/pexels-photo-1878293.jpeg"
  }
];

